apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-rest
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      # 60秒間でCPU使用率50%以下なら下げる
      stabilizationWindowSeconds: 60
      policies:
        # 60秒で最大2pod下げる
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleUp:
      # 60秒間でCPU使用率50%以上なら上げる
      stabilizationWindowSeconds: 60
      policies:
      # 60秒で最大2pod上げる
      - type: Pods
        value: 2
        periodSeconds: 60